language: python

notifications:
  email: false

env:
    - ENV="python=2.7"
    - ENV="python=2.6"

before_install:
    - pip install ipython[all]
    - git clone https://github.com/openalea/deploy
    - cd deploy
    - python setup.py install
    - cd ..

install: python multisetup.py develop

script: ./travis-tests.sh